= release owner的小助手

== 项目介绍
项目一共有三个小功能：

. 收集所有的release pipeline
. 检查指定的pipeline 是否已经部署了uat
. 检查指定的pipeline 是否点了 ready for release

== 项目动机
随着项目规模的越来越大， 团队之间的沟通成本越来越高。 release owner的担子越来越重了。 手动的去check每个服务是否部署，以及是否点了ready for release， 对release owner是个很大的工作量。

在这种release owner 频繁的更换的情况下，自动化工具愈发显得重要。

== 使用方式

. 检查所有的release pipeline
. 检查指定的release pipeline

=== 检查所有的release pipeline

. `npm run generatePipeline`
.. 生产所有的release pipeline
.. 执行成功之后在**./src**目录下会生成**pipeline.ts**文件， 后续的所有操作都是基于这个文件的。

=== 检查指定的release pipeline

. 修改/新建 **pipeline.ts**文件。 配置需要check的pipeline。

=== 其他相同部分

. `npm run checkDeployUat`
.. 检查所有在**pipeline.ts** 文件配置的pipeline，是否都在uat上部署了。
. `npm run checkReadyForRelease`
.. 检查所有在**pipeline.ts** 文件配置的pipeline，是否都点了**ready for release**， 以及点了**ready for release**的服务的名称和版本号，已经对应的pipeline trigger 人及邮箱。

WARNING: 开始之前，请完成下列配置

进入 **./src/config.ts**里修改
[source,typescript]
----
export const cookie: string = 'JSESSIONID=node0xxxxxxxxxxxxxxxxxxxxxxxx.node0' // 改为自己的，在chrome的storage里可以找到。
export const pipelineUrl: string = ''; // pipeline的URL
----

== demo

[source, bash]
.生成所有的pipeline
----
❯ npm run generatePipeline

> release-tools@1.0.0 generatePipeline /Users/lqqu/release-tools
> ts-node ./src/generatePipeline.ts

~/release-tools master* 9s ❯
----
. 检查uat的部署情况
[source, bash]
----
❯ npm run checkDeployUat

> release-tools@1.0.0 checkDeployUat /Users/lqqu/release-tools
> ts-node src/checkDeployUat.ts

<PIPELINE URL>/pipeline/activity/xxxx  not deploy uat

~/release-tools master* 8s ❯
----

. 检查ready for release点击情况
[source,bash]
----
❯ npm run checkReadyForRelease

> release-tools@1.0.0 checkReadyForRelease /Users/lqqu/release-tools
> ts-node ./src/checkReadyForRelease.ts

<PIPELINE URL>/pipeline/activity/<pipelineName> not ready for release
----------------------------
ready for release pipelines!
----------------------------
pipeline-name :pipelineVersion //@trigger User <user email>

tw.gocd-plus-release:73 //@XiaoQu <qulianqing1314@qq.com>
~/release-tools master* 7s ❯
----
